import { Phone } from "./PhoneModel";
import { phoneFullDTO, phoneSearchDTO } from "./PhoneDTO";
import { QueryResult, Pool } from 'pg';

import * as conf from '../../config'

export interface IPhoneRepository {
    getById(id: string, role: string): Promise<Phone | null>;
    paginate(props: Partial<phoneFullDTO>, pageNumber: number, pageSize: number, role: string): Promise<Phone[]>;
    create(phone: Phone, role: string): Promise<Phone>;
    update(phone: Phone, role: string): Promise<Phone | null>;
}

export class PostgresPhoneRepository implements IPhoneRepository {
    private pool: Pool;
    private seq: any;

	constructor() {
        this.pool = new Pool({
            user: conf.user,
            password: conf.password,
            host: conf.host,
            port: conf.port,
            database: conf.database
        });
    }

	async initialize(): Promise<void> {
        await this.ensureTableExists();
    }

	async ensureTableExists(): Promise<void> {
        const client = await this.pool.connect();
        try {
            // Проверяем, существует ли таблица
            const result = await client.query(
                `SELECT to_regclass('public.phones')`
            );

            if (!result.rows[0].to_regclass) {
                // Если таблица не существует, создаем ее
                await client.query(
                    `CREATE TABLE IF NOT EXISTS phones (
                        id SERIAL PRIMARY KEY,
                        name VARCHAR(255) NOT NULL,
                        producername VARCHAR(255) NOT NULL,
                        osname VARCHAR(255) NOT NULL,
                        ramsize INT NOT NULL CHECK (ramsize >= 0),
                        memsize INT NOT NULL CHECK (memsize >= 0),
                        camres INT NOT NULL CHECK (camres >= 0),
                        price INT NOT NULL CHECK (price >= 0),
                        warranty INT NOT NULL CHECK (warranty >= 0),
                        release_year INT NOT NULL CHECK (release_year >= 0),
                        type VARCHAR(255) NOT NULL,
                        model VARCHAR(255) NOT NULL,
                        producer_code VARCHAR(255) NOT NULL,
                        back_panel_color VARCHAR(255),
                        edge_color VARCHAR(255),
                        manufacturer_declared_color VARCHAR(255),
                        frequencies_2g VARCHAR(255),
                        frequencies_3g VARCHAR(255),
                        lte_4g_support VARCHAR(255),
                        frequencies_4g_lte VARCHAR(255),
                        lte_advanced_support VARCHAR(255),
                        lte_advanced_speed_categories VARCHAR(255),
                        volte_support VARCHAR(255),
                        networks_5g_support VARCHAR(255),
                        frequencies_5g VARCHAR(255),
                        sim_card_format VARCHAR(255),
                        physical_sim_cards_count INT NOT NULL CHECK (physical_sim_cards_count >= 0),
                        esim_count VARCHAR(255),
                        screen_size_inch decimal NOT NULL CHECK (screen_size_inch > 0),
                        screen_resolution VARCHAR(255),
                        screen_matrix_technology VARCHAR(255),
                        screen_matrix_type_detailed VARCHAR(255),
                        brightness INT NOT NULL CHECK (brightness >= 0),
                        screen_refresh_rate INT NOT NULL CHECK (screen_refresh_rate > 0),
                        pixel_density INT NOT NULL CHECK (pixel_density > 0),
                        aspect_ratio VARCHAR(255) NOT NULL,
                        screen_colors_count INT NOT NULL CHECK (screen_colors_count > 0),
                        body_type VARCHAR(255),
                        body_material VARCHAR(255),
                        ruggedness VARCHAR(255),
                        screen_protective_coating VARCHAR(255),
                        ip_rating VARCHAR(255),
                        screen_cutout_type VARCHAR(255),
                        os_version VARCHAR(255),
                        processor_model VARCHAR(255),
                        cores_count INT NOT NULL CHECK (cores_count > 0),
                        max_processor_frequency decimal NOT NULL CHECK (max_processor_frequency > 0),
                        processor_configuration VARCHAR(255),
                        fabrication_process VARCHAR(255),
                        gpu VARCHAR(255),
                        ram_type VARCHAR(255),
                        ram_amount INT NOT NULL CHECK (ram_amount > 0),
                        virtual_ram_extension VARCHAR(255),
                        internal_memory_amount INT NOT NULL CHECK (internal_memory_amount >= 0),
                        memory_card_slot VARCHAR(255),
                        main_cameras_count INT NOT NULL CHECK (main_cameras_count >= 0),
                        main_camera_megapixels VARCHAR(255),
                        camera_modules_type VARCHAR(255),
                        main_camera_sensor_model VARCHAR(255),
                        main_camera_aperture VARCHAR(255),
                        main_camera_autofocus VARCHAR(255),
                        flash_type VARCHAR(255),
                        lens_field_of_view_angle INT NOT NULL CHECK (lens_field_of_view_angle >= 0),
                        optical_stabilization VARCHAR(255),
                        digital_zoom_photo INT NOT NULL CHECK (digital_zoom_photo >= 0),
                        optical_zoom_photo VARCHAR(255),
                        main_camera_resolution VARCHAR(255),
                        dxomark_rating_main_camera INT NOT NULL CHECK (dxomark_rating_main_camera >= 0),
                        main_camera_features_technologies VARCHAR(255),
                        main_camera_shooting_modes_features VARCHAR(255),
                        video_shooting_format VARCHAR(255),
                        video_resolution_frame_rate VARCHAR(255),
                        slow_motion_video VARCHAR(255),
                        video_zoom VARCHAR(255),
                        video_playback_formats VARCHAR(255),
                        video_shooting_features_functions VARCHAR(255),
                        dual_front_camera VARCHAR(255),
                        front_camera_megapixels_count INT NOT NULL CHECK (front_camera_megapixels_count >= 0),
                        front_camera_aperture VARCHAR(255),
                        front_camera_autofocus VARCHAR(255),
                        built_in_flash VARCHAR(255),
                        front_camera_resolution VARCHAR(255),
                        dxomark_rating_selfie_camera INT NOT NULL CHECK (dxomark_rating_selfie_camera >= 0),
                        front_camera_features_technologies VARCHAR(255),
                        front_camera_shooting_modes_features VARCHAR(255),
                        stereo_speakers VARCHAR(255),
                        audio_file_formats VARCHAR(255),
                        fm_radio VARCHAR(255),
                        bluetooth_version VARCHAR(255),
                        wifi_standard VARCHAR(255),
                        nfc VARCHAR(255),
                        navigation_systems VARCHAR(255),
                        ir_port VARCHAR(255),
                        other_data_transmission_technologies VARCHAR(255),
                        charging_interface VARCHAR(255),
                        headphone_jack VARCHAR(255),
                        otg_support VARCHAR(255),
                        sensors VARCHAR(255),
                        battery_type VARCHAR(255),
                        battery_capacity VARCHAR(255),
                        charger_voltage VARCHAR(255),
                        charger_output_power VARCHAR(255),
                        fast_charging VARCHAR(255),
                        fast_charging_standards VARCHAR(255),
                        wireless_charging_support VARCHAR(255),
                        reverse_wireless_charging_support VARCHAR(255),
                        music_playback_time VARCHAR(255),
                        video_playback_time VARCHAR(255),
                        biometric_protection VARCHAR(255),
                        headphones_included VARCHAR(255),
                        charger_included VARCHAR(255),
                        package_contents VARCHAR(255),
                        led_notification_indicator VARCHAR(255),
                        additional_features VARCHAR(255),
                        dimensions_and_weight VARCHAR(255),
                        created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
                        updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
                    )`
                );
                console.log('Таблица телефонов создана');
            } else {
                console.log('Таблица телефонов уже существует');
            }
        } catch (error: any) {
            console.error('Ошибка при проверке таблицы телефонов:', error.message);
        } finally {
            client.release();
        }
    }

    async create(phone: Phone, role: string): Promise<Phone> {
        const client = await this.pool.connect();
        await client.query(`SET ROLE ${role}`);
        try {

            const result = await client.query(
                `INSERT INTO phones (
                    name,
                    producername,
                    osname,
                    ramsize,
                    memsize,
                    camres,
                    price,
                    warranty,
                    release_year,
                    type,
                    model,
                    producer_code,
                    back_panel_color,
                    edge_color,
                    manufacturer_declared_color,
                    frequencies_2g,
                    frequencies_3g,
                    lte_4g_support,
                    frequencies_4g_lte,
                    lte_advanced_support,
                    lte_advanced_speed_categories,
                    volte_support,
                    networks_5g_support,
                    frequencies_5g,
                    sim_card_format,
                    physical_sim_cards_count,
                    esim_count,
                    screen_size_inch,
                    screen_resolution,
                    screen_matrix_technology,
                    screen_matrix_type_detailed,
                    brightness,
                    screen_refresh_rate,
                    pixel_density,
                    aspect_ratio,
                    screen_colors_count,
                    body_type,
                    body_material,
                    ruggedness,
                    screen_protective_coating,
                    ip_rating,
                    screen_cutout_type,
                    os_version,
                    processor_model,
                    cores_count,
                    max_processor_frequency,
                    processor_configuration,
                    fabrication_process,
                    gpu,
                    ram_type,
                    ram_amount,
                    virtual_ram_extension,
                    internal_memory_amount,
                    memory_card_slot,
                    main_cameras_count,
                    main_camera_megapixels,
                    camera_modules_type,
                    main_camera_sensor_model,
                    main_camera_aperture,
                    main_camera_autofocus,
                    flash_type,
                    lens_field_of_view_angle,
                    optical_stabilization,
                    digital_zoom_photo,
                    optical_zoom_photo,
                    main_camera_resolution,
                    dxomark_rating_main_camera,
                    main_camera_features_technologies,
                    main_camera_shooting_modes_features,
                    video_shooting_format,
                    video_resolution_frame_rate,
                    slow_motion_video,
                    video_zoom,
                    video_playback_formats,
                    video_shooting_features_functions,
                    dual_front_camera,
                    front_camera_megapixels_count,
                    front_camera_aperture,
                    front_camera_autofocus,
                    built_in_flash,
                    front_camera_resolution,
                    dxomark_rating_selfie_camera,
                    front_camera_features_technologies,
                    front_camera_shooting_modes_features,
                    stereo_speakers,
                    audio_file_formats,
                    fm_radio,
                    bluetooth_version,
                    wifi_standard,
                    nfc,
                    navigation_systems,
                    ir_port,
                    other_data_transmission_technologies,
                    charging_interface,
                    headphone_jack,
                    otg_support,
                    sensors,
                    battery_type,
                    battery_capacity,
                    charger_voltage,
                    charger_output_power,
                    fast_charging,
                    fast_charging_standards,
                    wireless_charging_support,
                    reverse_wireless_charging_support,
                    music_playback_time,
                    video_playback_time,
                    biometric_protection,
                    headphones_included,
                    charger_included,
                    package_contents,
                    led_notification_indicator,
                    additional_features,
                    dimensions_and_weight
                ) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, $23, $24, $25, $26, $27, $28, $29, $30, $31, $32, $33, $34, $35, $36, $37, $38, $39, $40, $41, $42, $43, $44, $45, $46, $47, $48, $49, $50, $51, $52, $53, $54, $55, $56, $57, $58, $59, $60, $61, $62, $63, $64, $65, $66, $67, $68, $69, $70, $71, $72, $73, $74, $75, $76, $77, $78, $79, $80, $81, $82, $83, $84, $85, $86, $87, $88, $89, $90, $91, $92, $93, $94, $95, $96, $97, $98, $99, $100, $101, $102, $103, $104, $105, $106, $107, $108, $109, $110, $111, $112, $113, $114) RETURNING *`,
                [
                    phone.name,
                    phone.producername,
                    phone.osname,
                    phone.ramsize,
                    phone.memsize,
                    phone.camres,
                    phone.price,
                    phone.warranty,
                    phone.releaseYear,
                    phone.type,
                    phone.model,
                    phone.producerCode,
                    phone.backPanelColor,
                    phone.edgeColor,
                    phone.manufacturerDeclaredColor,
                    phone.frequencies2G,
                    phone.frequencies3G,
                    phone.lte4GSupport,
                    phone.frequencies4GLTE,
                    phone.lteAdvancedSupport,
                    phone.lteAdvancedSpeedCategories,
                    phone.volteSupport,
                    phone.networks5GSupport,
                    phone.frequencies5G,
                    phone.simCardFormat,
                    phone.physicalSimCardsCount,
                    phone.esimCount,
                    phone.screenSizeInch,
                    phone.screenResolution,
                    phone.screenMatrixTechnology,
                    phone.screenMatrixTypeDetailed,
                    phone.brightness,
                    phone.screenRefreshRate,
                    phone.pixelDensity,
                    phone.aspectRatio,
                    phone.screenColorsCount,
                    phone.bodyType,
                    phone.bodyMaterial,
                    phone.ruggedness,
                    phone.screenProtectiveCoating,
                    phone.ipRating,
                    phone.screenCutoutType,
                    phone.osVersion,
                    phone.processorModel,
                    phone.coresCount,
                    phone.maxProcessorFrequency,
                    phone.processorConfiguration,
                    phone.fabricationProcess,
                    phone.gpu,
                    phone.ramType,
                    phone.ramAmount,
                    phone.virtualRamExtension,
                    phone.internalMemoryAmount,
                    phone.memoryCardSlot,
                    phone.mainCamerasCount,
                    phone.mainCameraMegapixels,
                    phone.cameraModulesType,
                    phone.mainCameraSensorModel,
                    phone.mainCameraAperture,
                    phone.mainCameraAutofocus,
                    phone.flashType,
                    phone.lensFieldOfViewAngle,
                    phone.opticalStabilization,
                    phone.digitalZoomPhoto,
                    phone.opticalZoomPhoto,
                    phone.mainCameraResolution,
                    phone.dxomarkRatingMainCamera,
                    phone.mainCameraFeaturesTechnologies,
                    phone.mainCameraShootingModesFeatures,
                    phone.videoShootingFormat,
                    phone.videoResolutionFrameRate,
                    phone.slowMotionVideo,
                    phone.videoZoom,
                    phone.videoPlaybackFormats,
                    phone.videoShootingFeaturesFunctions,
                    phone.dualFrontCamera,
                    phone.frontCameraMegapixelsCount,
                    phone.frontCameraAperture,
                    phone.frontCameraAutofocus,
                    phone.builtInFlash,
                    phone.frontCameraResolution,
                    phone.dxomarkRatingSelfieCamera,
                    phone.frontCameraFeaturesTechnologies,
                    phone.frontCameraShootingModesFeatures,
                    phone.stereoSpeakers,
                    phone.audioFileFormats,
                    phone.fmRadio,
                    phone.bluetoothVersion,
                    phone.wifiStandard,
                    phone.nfc,
                    phone.navigationSystems,
                    phone.irPort,
                    phone.otherDataTransmissionTechnologies,
                    phone.chargingInterface,
                    phone.headphoneJack,
                    phone.otgSupport,
                    phone.sensors,
                    phone.batteryType,
                    phone.batteryCapacity,
                    phone.chargerVoltage,
                    phone.chargerOutputPower,
                    phone.fastCharging,
                    phone.fastChargingStandards,
                    phone.wirelessChargingSupport,
                    phone.reverseWirelessChargingSupport,
                    phone.musicPlaybackTime,
                    phone.videoPlaybackTime,
                    phone.biometricProtection,
                    phone.headphonesIncluded,
                    phone.chargerIncluded,
                    phone.packageContents,
                    phone.ledNotificationIndicator,
                    phone.additionalFeatures,
                    phone.dimensionsAndWeight
                ]
            );
            
            console.log(result.rows[0]);
    
            const phoneCreated = new Phone(
                result.rows[0].id,
                result.rows[0].name,
                result.rows[0].producername,
                result.rows[0].osname,
                result.rows[0].ramsize,
                result.rows[0].memsize,
                result.rows[0].camres,
                result.rows[0].price,
                result.rows[0].warranty,
                result.rows[0].release_year,
                result.rows[0].type,
                result.rows[0].model,
                result.rows[0].producer_code,
                result.rows[0].back_panel_color,
                result.rows[0].edge_color,
                result.rows[0].manufacturer_declared_color,
                result.rows[0].frequencies_2g,
                result.rows[0].frequencies_3g,
                result.rows[0].lte_4g_support,
                result.rows[0].frequencies_4g_lte,
                result.rows[0].lte_advanced_support,
                result.rows[0].lte_advanced_speed_categories,
                result.rows[0].volte_support,
                result.rows[0].networks_5g_support,
                result.rows[0].frequencies_5g,
                result.rows[0].sim_card_format,
                result.rows[0].physical_sim_cards_count,
                result.rows[0].esim_count,
                result.rows[0].screen_size_inch,
                result.rows[0].screen_resolution,
                result.rows[0].screen_matrix_technology,
                result.rows[0].screen_matrix_type_detailed,
                result.rows[0].brightness,
                result.rows[0].screen_refresh_rate,
                result.rows[0].pixel_density,
                result.rows[0].aspect_ratio,
                result.rows[0].screen_colors_count,
                result.rows[0].body_type,
                result.rows[0].body_material,
                result.rows[0].ruggedness,
                result.rows[0].screen_protective_coating,
                result.rows[0].ip_rating,
                result.rows[0].screen_cutout_type,
                result.rows[0].os_version,
                result.rows[0].processor_model,
                result.rows[0].cores_count,
                result.rows[0].max_processor_frequency,
                result.rows[0].processor_configuration,
                result.rows[0].fabrication_process,
                result.rows[0].gpu,
                result.rows[0].ram_type,
                result.rows[0].ram_amount,
                result.rows[0].virtual_ram_extension,
                result.rows[0].internal_memory_amount,
                result.rows[0].memory_card_slot,
                result.rows[0].main_cameras_count,
                result.rows[0].main_camera_megapixels,
                result.rows[0].camera_modules_type,
                result.rows[0].main_camera_sensor_model,
                result.rows[0].main_camera_aperture,
                result.rows[0].main_camera_autofocus,
                result.rows[0].flash_type,
                result.rows[0].lens_field_of_view_angle,
                result.rows[0].optical_stabilization,
                result.rows[0].digital_zoom_photo,
                result.rows[0].optical_zoom_photo,
                result.rows[0].main_camera_resolution,
                result.rows[0].dxomark_rating_main_camera,
                result.rows[0].main_camera_features_technologies,
                result.rows[0].main_camera_shooting_modes_features,
                result.rows[0].video_shooting_format,
                result.rows[0].video_resolution_frame_rate,
                result.rows[0].slow_motion_video,
                result.rows[0].video_zoom,
                result.rows[0].video_playback_formats,
                result.rows[0].video_shooting_features_functions,
                result.rows[0].dual_front_camera,
                result.rows[0].front_camera_megapixels_count,
                result.rows[0].front_camera_aperture,
                result.rows[0].front_camera_autofocus,
                result.rows[0].built_in_flash,
                result.rows[0].front_camera_resolution,
                result.rows[0].dxomark_rating_selfie_camera,
                result.rows[0].front_camera_features_technologies,
                result.rows[0].front_camera_shooting_modes_features,
                result.rows[0].stereo_speakers,
                result.rows[0].audio_file_formats,
                result.rows[0].fm_radio,
                result.rows[0].bluetooth_version,
                result.rows[0].wifi_standard,
                result.rows[0].nfc,
                result.rows[0].navigation_systems,
                result.rows[0].ir_port,
                result.rows[0].other_data_transmission_technologies,
                result.rows[0].charging_interface,
                result.rows[0].headphone_jack,
                result.rows[0].otg_support,
                result.rows[0].sensors,
                result.rows[0].battery_type,
                result.rows[0].battery_capacity,
                result.rows[0].charger_voltage,
                result.rows[0].charger_output_power,
                result.rows[0].fast_charging,
                result.rows[0].fast_charging_standards,
                result.rows[0].wireless_charging_support,
                result.rows[0].reverse_wireless_charging_support,
                result.rows[0].music_playback_time,
                result.rows[0].video_playback_time,
                result.rows[0].biometric_protection,
                result.rows[0].headphones_included,
                result.rows[0].charger_included,
                result.rows[0].package_contents,
                result.rows[0].led_notification_indicator,
                result.rows[0].additional_features,
                result.rows[0].dimensions_and_weight
            );
    
            return phoneCreated;
        } finally {
            client.release();
        }
    }
    

    async update(phone: Phone, role: string): Promise<Phone | null> {
        try {
            // Проверка, что пользователь существует
            if (!phone.id) {
                throw new Error('ID телефона не указан');
            }

            const client = await this.pool.connect();
            await client.query(`SET ROLE ${role}`);
            const result = await client.query(
                `UPDATE phones 
                 SET 
                    name = $1, 
                    producername = $2, 
                    osname = $3, 
                    ramsize = $4, 
                    memsize = $5, 
                    camres = $6, 
                    price = $7, 
                    warranty = $8, 
                    release_year = $9, 
                    type = $10, 
                    model = $11, 
                    producer_code = $12, 
                    back_panel_color = $13, 
                    edge_color = $14, 
                    manufacturer_declared_color = $15, 
                    frequencies_2g = $16, 
                    frequencies_3g = $17, 
                    lte_4g_support = $18, 
                    frequencies_4g_lte = $19, 
                    lte_advanced_support = $20, 
                    lte_advanced_speed_categories = $21, 
                    volte_support = $22, 
                    networks_5g_support = $23, 
                    frequencies_5g = $24, 
                    sim_card_format = $25, 
                    physical_sim_cards_count = $26, 
                    esim_count = $27, 
                    screen_size_inch = $28, 
                    screen_resolution = $29, 
                    screen_matrix_technology = $30, 
                    screen_matrix_type_detailed = $31, 
                    brightness = $32, 
                    screen_refresh_rate = $33, 
                    pixel_density = $34, 
                    aspect_ratio = $35, 
                    screen_colors_count = $36, 
                    body_type = $37, 
                    body_material = $38, 
                    ruggedness = $39, 
                    screen_protective_coating = $40, 
                    ip_rating = $41, 
                    screen_cutout_type = $42, 
                    os_version = $43, 
                    processor_model = $44, 
                    cores_count = $45, 
                    max_processor_frequency = $46, 
                    processor_configuration = $47, 
                    fabrication_process = $48, 
                    gpu = $49, 
                    ram_type = $50, 
                    ram_amount = $51, 
                    virtual_ram_extension = $52, 
                    internal_memory_amount = $53, 
                    memory_card_slot = $54, 
                    main_cameras_count = $55, 
                    main_camera_megapixels = $56, 
                    camera_modules_type = $57, 
                    main_camera_sensor_model = $58, 
                    main_camera_aperture = $59, 
                    main_camera_autofocus = $60, 
                    flash_type = $61, 
                    lens_field_of_view_angle = $62, 
                    optical_stabilization = $63, 
                    digital_zoom_photo = $64, 
                    optical_zoom_photo = $65, 
                    main_camera_resolution = $66, 
                    dxomark_rating_main_camera = $67, 
                    main_camera_features_technologies = $68, 
                    main_camera_shooting_modes_features = $69, 
                    video_shooting_format = $70, 
                    video_resolution_frame_rate = $71, 
                    slow_motion_video = $72, 
                    video_zoom = $73, 
                    video_playback_formats = $74, 
                    video_shooting_features_functions = $75, 
                    dual_front_camera = $76, 
                    front_camera_megapixels_count = $77, 
                    front_camera_aperture = $78, 
                    front_camera_autofocus = $79, 
                    built_in_flash = $80, 
                    front_camera_resolution = $81, 
                    dxomark_rating_selfie_camera = $82, 
                    front_camera_features_technologies = $83, 
                    front_camera_shooting_modes_features = $84, 
                    stereo_speakers = $85, 
                    audio_file_formats = $86, 
                    fm_radio = $87, 
                    bluetooth_version = $88, 
                    wifi_standard = $89, 
                    nfc = $90, 
                    navigation_systems = $91, 
                    ir_port = $92, 
                    other_data_transmission_technologies = $93, 
                    charging_interface = $94, 
                    headphone_jack = $95, 
                    otg_support = $96, 
                    sensors = $97, 
                    battery_type = $98, 
                    battery_capacity = $99, 
                    charger_voltage = $100, 
                    charger_output_power = $101, 
                    fast_charging = $102, 
                    fast_charging_standards = $103, 
                    wireless_charging_support = $104, 
                    reverse_wireless_charging_support = $105, 
                    music_playback_time = $106, 
                    video_playback_time = $107, 
                    biometric_protection = $108, 
                    headphones_included = $109, 
                    charger_included = $110, 
                    package_contents = $111, 
                    led_notification_indicator = $112, 
                    additional_features = $113, 
                    dimensions_and_weight = $114, 
                    updated_at = CURRENT_TIMESTAMP 
                 WHERE id = $115 
                 RETURNING *`,
                [
                    phone.name,
                    phone.producername,
                    phone.osname,
                    phone.ramsize,
                    phone.memsize,
                    phone.camres,
                    phone.price,
                    phone.warranty,
                    phone.releaseYear,
                    phone.type,
                    phone.model,
                    phone.producerCode,
                    phone.backPanelColor,
                    phone.edgeColor,
                    phone.manufacturerDeclaredColor,
                    phone.frequencies2G,
                    phone.frequencies3G,
                    phone.lte4GSupport,
                    phone.frequencies4GLTE,
                    phone.lteAdvancedSupport,
                    phone.lteAdvancedSpeedCategories,
                    phone.volteSupport,
                    phone.networks5GSupport,
                    phone.frequencies5G,
                    phone.simCardFormat,
                    phone.physicalSimCardsCount,
                    phone.esimCount,
                    phone.screenSizeInch,
                    phone.screenResolution,
                    phone.screenMatrixTechnology,
                    phone.screenMatrixTypeDetailed,
                    phone.brightness,
                    phone.screenRefreshRate,
                    phone.pixelDensity,
                    phone.aspectRatio,
                    phone.screenColorsCount,
                    phone.bodyType,
                    phone.bodyMaterial,
                    phone.ruggedness,
                    phone.screenProtectiveCoating,
                    phone.ipRating,
                    phone.screenCutoutType,
                    phone.osVersion,
                    phone.processorModel,
                    phone.coresCount,
                    phone.maxProcessorFrequency,
                    phone.processorConfiguration,
                    phone.fabricationProcess,
                    phone.gpu,
                    phone.ramType,
                    phone.ramAmount,
                    phone.virtualRamExtension,
                    phone.internalMemoryAmount,
                    phone.memoryCardSlot,
                    phone.mainCamerasCount,
                    phone.mainCameraMegapixels,
                    phone.cameraModulesType,
                    phone.mainCameraSensorModel,
                    phone.mainCameraAperture,
                    phone.mainCameraAutofocus,
                    phone.flashType,
                    phone.lensFieldOfViewAngle,
                    phone.opticalStabilization,
                    phone.digitalZoomPhoto,
                    phone.opticalZoomPhoto,
                    phone.mainCameraResolution,
                    phone.dxomarkRatingMainCamera,
                    phone.mainCameraFeaturesTechnologies,
                    phone.mainCameraShootingModesFeatures,
                    phone.videoShootingFormat,
                    phone.videoResolutionFrameRate,
                    phone.slowMotionVideo,
                    phone.videoZoom,
                    phone.videoPlaybackFormats,
                    phone.videoShootingFeaturesFunctions,
                    phone.dualFrontCamera,
                    phone.frontCameraMegapixelsCount,
                    phone.frontCameraAperture,
                    phone.frontCameraAutofocus,
                    phone.builtInFlash,
                    phone.frontCameraResolution,
                    phone.dxomarkRatingSelfieCamera,
                    phone.frontCameraFeaturesTechnologies,
                    phone.frontCameraShootingModesFeatures,
                    phone.stereoSpeakers,
                    phone.audioFileFormats,
                    phone.fmRadio,
                    phone.bluetoothVersion,
                    phone.wifiStandard,
                    phone.nfc,
                    phone.navigationSystems,
                    phone.irPort,
                    phone.otherDataTransmissionTechnologies,
                    phone.chargingInterface,
                    phone.headphoneJack,
                    phone.otgSupport,
                    phone.sensors,
                    phone.batteryType,
                    phone.batteryCapacity,
                    phone.chargerVoltage,
                    phone.chargerOutputPower,
                    phone.fastCharging,
                    phone.fastChargingStandards,
                    phone.wirelessChargingSupport,
                    phone.reverseWirelessChargingSupport,
                    phone.musicPlaybackTime,
                    phone.videoPlaybackTime,
                    phone.biometricProtection,
                    phone.headphonesIncluded,
                    phone.chargerIncluded,
                    phone.packageContents,
                    phone.ledNotificationIndicator,
                    phone.additionalFeatures,
                    phone.dimensionsAndWeight,
                    phone.id
                ]
            );

            client.release();

            if (result.rows.length === 0) {
                throw new Error('Телефон не найден');
            }

            let phoneUpdated = new Phone(
                result.rows[0].id,
                result.rows[0].name,
                result.rows[0].producername,
                result.rows[0].osname,
                result.rows[0].ramsize,
                result.rows[0].memsize,
                result.rows[0].camres,
                result.rows[0].price,
                result.rows[0].warranty,
                result.rows[0].release_year,
                result.rows[0].type,
                result.rows[0].model,
                result.rows[0].producer_code,
                result.rows[0].back_panel_color,
                result.rows[0].edge_color,
                result.rows[0].manufacturer_declared_color,
                result.rows[0].frequencies_2g,
                result.rows[0].frequencies_3g,
                result.rows[0].lte_4g_support,
                result.rows[0].frequencies_4g_lte,
                result.rows[0].lte_advanced_support,
                result.rows[0].lte_advanced_speed_categories,
                result.rows[0].volte_support,
                result.rows[0].networks_5g_support,
                result.rows[0].frequencies_5g,
                result.rows[0].sim_card_format,
                result.rows[0].physical_sim_cards_count,
                result.rows[0].esim_count,
                result.rows[0].screen_size_inch,
                result.rows[0].screen_resolution,
                result.rows[0].screen_matrix_technology,
                result.rows[0].screen_matrix_type_detailed,
                result.rows[0].brightness,
                result.rows[0].screen_refresh_rate,
                result.rows[0].pixel_density,
                result.rows[0].aspect_ratio,
                result.rows[0].screen_colors_count,
                result.rows[0].body_type,
                result.rows[0].body_material,
                result.rows[0].ruggedness,
                result.rows[0].screen_protective_coating,
                result.rows[0].ip_rating,
                result.rows[0].screen_cutout_type,
                result.rows[0].os_version,
                result.rows[0].processor_model,
                result.rows[0].cores_count,
                result.rows[0].max_processor_frequency,
                result.rows[0].processor_configuration,
                result.rows[0].fabrication_process,
                result.rows[0].gpu,
                result.rows[0].ram_type,
                result.rows[0].ram_amount,
                result.rows[0].virtual_ram_extension,
                result.rows[0].internal_memory_amount,
                result.rows[0].memory_card_slot,
                result.rows[0].main_cameras_count,
                result.rows[0].main_camera_megapixels,
                result.rows[0].camera_modules_type,
                result.rows[0].main_camera_sensor_model,
                result.rows[0].main_camera_aperture,
                result.rows[0].main_camera_autofocus,
                result.rows[0].flash_type,
                result.rows[0].lens_field_of_view_angle,
                result.rows[0].optical_stabilization,
                result.rows[0].digital_zoom_photo,
                result.rows[0].optical_zoom_photo,
                result.rows[0].main_camera_resolution,
                result.rows[0].dxomark_rating_main_camera,
                result.rows[0].main_camera_features_technologies,
                result.rows[0].main_camera_shooting_modes_features,
                result.rows[0].video_shooting_format,
                result.rows[0].video_resolution_frame_rate,
                result.rows[0].slow_motion_video,
                result.rows[0].video_zoom,
                result.rows[0].video_playback_formats,
                result.rows[0].video_shooting_features_functions,
                result.rows[0].dual_front_camera,
                result.rows[0].front_camera_megapixels_count,
                result.rows[0].front_camera_aperture,
                result.rows[0].front_camera_autofocus,
                result.rows[0].built_in_flash,
                result.rows[0].front_camera_resolution,
                result.rows[0].dxomark_rating_selfie_camera,
                result.rows[0].front_camera_features_technologies,
                result.rows[0].front_camera_shooting_modes_features,
                result.rows[0].stereo_speakers,
                result.rows[0].audio_file_formats,
                result.rows[0].fm_radio,
                result.rows[0].bluetooth_version,
                result.rows[0].wifi_standard,
                result.rows[0].nfc,
                result.rows[0].navigation_systems,
                result.rows[0].ir_port,
                result.rows[0].other_data_transmission_technologies,
                result.rows[0].charging_interface,
                result.rows[0].headphone_jack,
                result.rows[0].otg_support,
                result.rows[0].sensors,
                result.rows[0].battery_type,
                result.rows[0].battery_capacity,
                result.rows[0].charger_voltage,
                result.rows[0].charger_output_power,
                result.rows[0].fast_charging,
                result.rows[0].fast_charging_standards,
                result.rows[0].wireless_charging_support,
                result.rows[0].reverse_wireless_charging_support,
                result.rows[0].music_playback_time,
                result.rows[0].video_playback_time,
                result.rows[0].biometric_protection,
                result.rows[0].headphones_included,
                result.rows[0].charger_included,
                result.rows[0].package_contents,
                result.rows[0].led_notification_indicator,
                result.rows[0].additional_features,
                result.rows[0].dimensions_and_weight
            );
            return phoneUpdated;
        } catch (error: any) {
            console.error('Ошибка при обновлении телефона:', error.message);
            return null;
        }
    }

    async getById(id: string, role: string): Promise<Phone | null> {
        try {
            // Валидация входных данных
            if (!id) {
                throw new Error('ID телефона не указан');
            }

            const client = await this.pool.connect();
            await client.query(`SET ROLE ${role}`);
            const result = await client.query(
                `SELECT * FROM phones WHERE id = $1`,
                [parseInt(id)]
            );

            client.release();

            if (result.rows.length === 0) {
                throw new Error('Телефон с указанным ID не найден');
            }

            let toParse = result.rows[0];
            let phoneGetted = new Phone(
                result.rows[0].id,
                result.rows[0].name,
                result.rows[0].producername,
                result.rows[0].osname,
                result.rows[0].ramsize,
                result.rows[0].memsize,
                result.rows[0].camres,
                result.rows[0].price,
                result.rows[0].warranty,
                result.rows[0].release_year,
                result.rows[0].type,
                result.rows[0].model,
                result.rows[0].producer_code,
                result.rows[0].back_panel_color,
                result.rows[0].edge_color,
                result.rows[0].manufacturer_declared_color,
                result.rows[0].frequencies_2g,
                result.rows[0].frequencies_3g,
                result.rows[0].lte_4g_support,
                result.rows[0].frequencies_4g_lte,
                result.rows[0].lte_advanced_support,
                result.rows[0].lte_advanced_speed_categories,
                result.rows[0].volte_support,
                result.rows[0].networks_5g_support,
                result.rows[0].frequencies_5g,
                result.rows[0].sim_card_format,
                result.rows[0].physical_sim_cards_count,
                result.rows[0].esim_count,
                result.rows[0].screen_size_inch,
                result.rows[0].screen_resolution,
                result.rows[0].screen_matrix_technology,
                result.rows[0].screen_matrix_type_detailed,
                result.rows[0].brightness,
                result.rows[0].screen_refresh_rate,
                result.rows[0].pixel_density,
                result.rows[0].aspect_ratio,
                result.rows[0].screen_colors_count,
                result.rows[0].body_type,
                result.rows[0].body_material,
                result.rows[0].ruggedness,
                result.rows[0].screen_protective_coating,
                result.rows[0].ip_rating,
                result.rows[0].screen_cutout_type,
                result.rows[0].os_version,
                result.rows[0].processor_model,
                result.rows[0].cores_count,
                result.rows[0].max_processor_frequency,
                result.rows[0].processor_configuration,
                result.rows[0].fabrication_process,
                result.rows[0].gpu,
                result.rows[0].ram_type,
                result.rows[0].ram_amount,
                result.rows[0].virtual_ram_extension,
                result.rows[0].internal_memory_amount,
                result.rows[0].memory_card_slot,
                result.rows[0].main_cameras_count,
                result.rows[0].main_camera_megapixels,
                result.rows[0].camera_modules_type,
                result.rows[0].main_camera_sensor_model,
                result.rows[0].main_camera_aperture,
                result.rows[0].main_camera_autofocus,
                result.rows[0].flash_type,
                result.rows[0].lens_field_of_view_angle,
                result.rows[0].optical_stabilization,
                result.rows[0].digital_zoom_photo,
                result.rows[0].optical_zoom_photo,
                result.rows[0].main_camera_resolution,
                result.rows[0].dxomark_rating_main_camera,
                result.rows[0].main_camera_features_technologies,
                result.rows[0].main_camera_shooting_modes_features,
                result.rows[0].video_shooting_format,
                result.rows[0].video_resolution_frame_rate,
                result.rows[0].slow_motion_video,
                result.rows[0].video_zoom,
                result.rows[0].video_playback_formats,
                result.rows[0].video_shooting_features_functions,
                result.rows[0].dual_front_camera,
                result.rows[0].front_camera_megapixels_count,
                result.rows[0].front_camera_aperture,
                result.rows[0].front_camera_autofocus,
                result.rows[0].built_in_flash,
                result.rows[0].front_camera_resolution,
                result.rows[0].dxomark_rating_selfie_camera,
                result.rows[0].front_camera_features_technologies,
                result.rows[0].front_camera_shooting_modes_features,
                result.rows[0].stereo_speakers,
                result.rows[0].audio_file_formats,
                result.rows[0].fm_radio,
                result.rows[0].bluetooth_version,
                result.rows[0].wifi_standard,
                result.rows[0].nfc,
                result.rows[0].navigation_systems,
                result.rows[0].ir_port,
                result.rows[0].other_data_transmission_technologies,
                result.rows[0].charging_interface,
                result.rows[0].headphone_jack,
                result.rows[0].otg_support,
                result.rows[0].sensors,
                result.rows[0].battery_type,
                result.rows[0].battery_capacity,
                result.rows[0].charger_voltage,
                result.rows[0].charger_output_power,
                result.rows[0].fast_charging,
                result.rows[0].fast_charging_standards,
                result.rows[0].wireless_charging_support,
                result.rows[0].reverse_wireless_charging_support,
                result.rows[0].music_playback_time,
                result.rows[0].video_playback_time,
                result.rows[0].biometric_protection,
                result.rows[0].headphones_included,
                result.rows[0].charger_included,
                result.rows[0].package_contents,
                result.rows[0].led_notification_indicator,
                result.rows[0].additional_features,
                result.rows[0].dimensions_and_weight
            );
            return phoneGetted;
        } catch (error: any) {
            console.error('Ошибка при поиске телефона по ID:', error.message);
            return null;
        }
    }
    async paginate(props: phoneSearchDTO, pageNumber: number, pageSize: number, role: string): Promise<Phone[]> {
        const offset = (pageNumber - 1) * pageSize;
    
        console.log(props, pageNumber, pageSize);
    
        let query = `SELECT * FROM phones`;
    
        const conditions: string[] = [];
        const values: any[] = [];
    
        if (props.name) {
            conditions.push(`name ILIKE $${values.length + 1}`);
            values.push(`%${props.name}%`);
        }
    
        if (props.producername) {
            conditions.push(`producername ILIKE $${values.length + 1}`);
            values.push(`%${props.producername}%`);
        }
    
        if (props.osname) {
            conditions.push(`osname ILIKE $${values.length + 1}`);
            values.push(`%${props.osname}%`);
        }
    
        if (props.minramsize !== undefined) {
            conditions.push(`ramsize >= $${values.length + 1}`);
            values.push(props.minramsize);
        }
    
        if (props.maxramsize !== undefined) {
            conditions.push(`ramsize <= $${values.length + 1}`);
            values.push(props.maxramsize);
        }
    
        if (props.minmemsize !== undefined) {
            conditions.push(`memsize >= $${values.length + 1}`);
            values.push(props.minmemsize);
        }
    
        if (props.maxmemsize !== undefined) {
            conditions.push(`memsize <= $${values.length + 1}`);
            values.push(props.maxmemsize);
        }
    
        if (props.mincamres !== undefined) {
            conditions.push(`camres >= $${values.length + 1}`);
            values.push(props.mincamres);
        }
    
        if (props.maxcamres !== undefined) {
            conditions.push(`camres <= $${values.length + 1}`);
            values.push(props.maxcamres);
        }
    
        if (props.minPrice !== undefined) {
            conditions.push(`price >= $${values.length + 1}`);
            values.push(props.minPrice);
        }
    
        if (props.maxPrice !== undefined) {
            conditions.push(`price <= $${values.length + 1}`);
            values.push(props.maxPrice);
        }
    
        if (conditions.length > 0) {
            query += ` WHERE ${conditions.join(' AND ')}`;
        }
    
        query += ` ORDER BY id`;
    
        if (pageSize !== undefined) {
            query += ` LIMIT $${values.length + 1} OFFSET $${values.length + 2}`;
            values.push(pageSize, offset);
        }
    
        const client = await this.pool.connect();
        await client.query(`SET ROLE ${role}`);
        try {
            const result = await client.query(query, values);
            let phonesToRet: Phone[] = [];
            for (let i = 0; i < result.rows.length; i++){
                phonesToRet.push(
                    new Phone(
                        result.rows[i].id,
                        result.rows[i].name,
                        result.rows[i].producername,
                        result.rows[i].osname,
                        result.rows[i].ramsize,
                        result.rows[i].memsize,
                        result.rows[i].camres,
                        result.rows[i].price,
                        result.rows[i].warranty,
                        result.rows[i].release_year,
                        result.rows[i].type,
                        result.rows[i].model,
                        result.rows[i].producer_code,
                        result.rows[i].back_panel_color,
                        result.rows[i].edge_color,
                        result.rows[i].manufacturer_declared_color,
                        result.rows[i].frequencies_2g,
                        result.rows[i].frequencies_3g,
                        result.rows[i].lte_4g_support,
                        result.rows[i].frequencies_4g_lte,
                        result.rows[i].lte_advanced_support,
                        result.rows[i].lte_advanced_speed_categories,
                        result.rows[i].volte_support,
                        result.rows[i].networks_5g_support,
                        result.rows[i].frequencies_5g,
                        result.rows[i].sim_card_format,
                        result.rows[i].physical_sim_cards_count,
                        result.rows[i].esim_count,
                        result.rows[i].screen_size_inch,
                        result.rows[i].screen_resolution,
                        result.rows[i].screen_matrix_technology,
                        result.rows[i].screen_matrix_type_detailed,
                        result.rows[i].brightness,
                        result.rows[i].screen_refresh_rate,
                        result.rows[i].pixel_density,
                        result.rows[i].aspect_ratio,
                        result.rows[i].screen_colors_count,
                        result.rows[i].body_type,
                        result.rows[i].body_material,
                        result.rows[i].ruggedness,
                        result.rows[i].screen_protective_coating,
                        result.rows[i].ip_rating,
                        result.rows[i].screen_cutout_type,
                        result.rows[i].os_version,
                        result.rows[i].processor_model,
                        result.rows[i].cores_count,
                        result.rows[i].max_processor_frequency,
                        result.rows[i].processor_configuration,
                        result.rows[i].fabrication_process,
                        result.rows[i].gpu,
                        result.rows[i].ram_type,
                        result.rows[i].ram_amount,
                        result.rows[i].virtual_ram_extension,
                        result.rows[i].internal_memory_amount,
                        result.rows[i].memory_card_slot,
                        result.rows[i].main_cameras_count,
                        result.rows[i].main_camera_megapixels,
                        result.rows[i].camera_modules_type,
                        result.rows[i].main_camera_sensor_model,
                        result.rows[i].main_camera_aperture,
                        result.rows[i].main_camera_autofocus,
                        result.rows[i].flash_type,
                        result.rows[i].lens_field_of_view_angle,
                        result.rows[i].optical_stabilization,
                        result.rows[i].digital_zoom_photo,
                        result.rows[i].optical_zoom_photo,
                        result.rows[i].main_camera_resolution,
                        result.rows[i].dxomark_rating_main_camera,
                        result.rows[i].main_camera_features_technologies,
                        result.rows[i].main_camera_shooting_modes_features,
                        result.rows[i].video_shooting_format,
                        result.rows[i].video_resolution_frame_rate,
                        result.rows[i].slow_motion_video,
                        result.rows[i].video_zoom,
                        result.rows[i].video_playback_formats,
                        result.rows[i].video_shooting_features_functions,
                        result.rows[i].dual_front_camera,
                        result.rows[i].front_camera_megapixels_count,
                        result.rows[i].front_camera_aperture,
                        result.rows[i].front_camera_autofocus,
                        result.rows[i].built_in_flash,
                        result.rows[i].front_camera_resolution,
                        result.rows[i].dxomark_rating_selfie_camera,
                        result.rows[i].front_camera_features_technologies,
                        result.rows[i].front_camera_shooting_modes_features,
                        result.rows[i].stereo_speakers,
                        result.rows[i].audio_file_formats,
                        result.rows[i].fm_radio,
                        result.rows[i].bluetooth_version,
                        result.rows[i].wifi_standard,
                        result.rows[i].nfc,
                        result.rows[i].navigation_systems,
                        result.rows[i].ir_port,
                        result.rows[i].other_data_transmission_technologies,
                        result.rows[i].charging_interface,
                        result.rows[i].headphone_jack,
                        result.rows[i].otg_support,
                        result.rows[i].sensors,
                        result.rows[i].battery_type,
                        result.rows[i].battery_capacity,
                        result.rows[i].charger_voltage,
                        result.rows[i].charger_output_power,
                        result.rows[i].fast_charging,
                        result.rows[i].fast_charging_standards,
                        result.rows[i].wireless_charging_support,
                        result.rows[i].reverse_wireless_charging_support,
                        result.rows[i].music_playback_time,
                        result.rows[i].video_playback_time,
                        result.rows[i].biometric_protection,
                        result.rows[i].headphones_included,
                        result.rows[i].charger_included,
                        result.rows[i].package_contents,
                        result.rows[i].led_notification_indicator,
                        result.rows[i].additional_features,
                        result.rows[i].dimensions_and_weight
                    )
                )
            }
            return phonesToRet;
        } catch (error: any) {
            console.error('Ошибка при поиске телефонов:', error.message);
            return [];
        } finally {
            client.release();
        }
    }
}    