CREATE ROLE shop_admin LOGIN PASSWORD 'admin_password';
CREATE ROLE user LOGIN PASSWORD 'user_password';
CREATE ROLE seller LOGIN PASSWORD 'seller_password';
CREATE ROLE guest;

GRANT ALL PRIVILEGES ON DATABASE public TO shop_admin;
GRANT SELECT, INSERT ON TABLE USERS TO public;

GRANT UPDATE ON TABLE USERS TO user, seller;

GRANT SELECT ON TABLE PHONES TO public;
GRANT SELECT, INSERT, DELETE ON TABLE WISHES TO user;
GRANT SELECT, INSERT ON TABLE PAYMENTS TO user;
GRANT UPDATE ON TABLE PAYMENTS TO seller
GRANT SELECT, INSERT, UPDATE ON TABLE ORDERS TO user, seller;
GRANT SELECT, INSERT, UPDATE ON TABLE POSITIONS TO USER, SELEER;
GRANT SELECT, INSERT, UPDATE ON TABLE BASKETS TO user, seller;
GRANT SELECT, INSERT, UPDATE ON TABLE BASKETPOSITIONS TO USER, SELEER;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE COMMENTS TO USER;
GRANT SELECT ON TABLE COMMENTS TO GUEST, SELLER;